name: Automated API tests using Postman CLI (manual)

on:
  workflow_dispatch:       # можна ще й руками запускати
    inputs:                # 👈 всередині workflow_dispatch
      job:
        description: "Which job to run"
        required: true
        default: "Reward"
        type: choice
        options:
          - Reward
          - Promocode
          - RandomBox
          - LuckyBox
          - GoldSeeker
          - CashClash
          - Payment
jobs:
  Reward:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.job == 'All' || github.event.inputs.job == 'Reward' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API Reward test
        run: newman run "https://api.postman.com/collections/33038645-27ddebd5-29f1-4977-a286-d0128bae9d4e?access_key=${{ secrets.POSTMAN_API_KEY }}" --folder "Reward" --globals workspace.postman_globals.json

  Promocode:
    # needs: [Reward]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.job == 'All' || github.event.inputs.job == 'Promocode' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API Promocode test
        run: newman run "https://api.postman.com/collections/33038645-27ddebd5-29f1-4977-a286-d0128bae9d4e?access_key=${{ secrets.POSTMAN_API_KEY }}" --folder "Promocode" --globals workspace.postman_globals.json

  RandomBox:
    # needs: [Reward, Promocode]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.job == 'All' || github.event.inputs.job == 'RandomBox' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API Random Box test
        run: newman run "https://api.postman.com/collections/33038645-27ddebd5-29f1-4977-a286-d0128bae9d4e?access_key=${{ secrets.POSTMAN_API_KEY }}" --folder "Random Box" --globals workspace.postman_globals.json

  LuckyBox:
    # needs: [Reward, Promocode, RandomBox]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.job == 'All' || github.event.inputs.job == 'LuckyBox' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API Lucky Box test
        run: newman run "https://api.postman.com/collections/33038645-27ddebd5-29f1-4977-a286-d0128bae9d4e?access_key=${{ secrets.POSTMAN_API_KEY }}" --folder "Lucky Box" --globals workspace.postman_globals.json

  GoldSeeker:
    # needs: [Reward, Promocode, RandomBox, LuckyBox]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.job == 'All' || github.event.inputs.job == 'GoldSeeker' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API Gold Seeker test
        run: newman run "https://api.postman.com/collections/33038645-27ddebd5-29f1-4977-a286-d0128bae9d4e?access_key=${{ secrets.POSTMAN_API_KEY }}" --folder "Gold Seeker" --globals workspace.postman_globals.json
  CashClash:
    # needs: [Reward, Promocode, RandomBox, LuckyBox, GoldSeeker]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.job == 'All' || github.event.inputs.job == 'CashClash' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API Cash Clash test
        run: newman run "https://api.postman.com/collections/33038645-27ddebd5-29f1-4977-a286-d0128bae9d4e?access_key=${{ secrets.POSTMAN_API_KEY }}" --folder "Cash Clash" --globals workspace.postman_globals.json

  Payment:
    # needs: [Reward, Promocode, RandomBox, LuckyBox, GoldSeeker,CashClash]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.job == 'All' || github.event.inputs.job == 'Payment' }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API Payment test
        run: newman run "https://api.postman.com/collections/33038645-27ddebd5-29f1-4977-a286-d0128bae9d4e?access_key=${{ secrets.POSTMAN_API_KEY }}" --folder "Payment" --globals workspace.postman_globals.json